apiVersion: v1
kind: ConfigMap
metadata:
  name: facturation-config
data:
  DJANGO_SETTINGS_MODULE: finance_manager.settings
  DATABASE_URL: postgresql://facturation_pme_user:change_me_password@facturation-db:5432/facturation_pme
  SECRET_KEY: your-secret-key-here
  DEBUG: "False"
  ALLOWED_HOSTS: "*"