---
app_name: facturation_pme
app_user: facturation_pme
app_group: facturation_pme
app_dir: /opt/facturation_pme
app_venv: "{{ app_dir }}/venv"

# Git
git_repo: https://github.com/frederickmeyapiiii/Accounting-saas.git
git_branch: main

# Django
django_secret_key: "change_me_production_secret_key_12345"
django_debug: "False"
django_allowed_hosts: "localhost,127.0.0.1,facturation.example.com"

# Database
db_engine: django.db.backends.postgresql
db_name: facturation_pme
db_user: facturation_pme_user
db_password: "change_me_db_password"
db_host: localhost
db_port: 5432

# Ports
gunicorn_port: 8000
nginx_port: 80
