[web_servers]
facturation_pme_prod ansible_host=192.168.1.100 ansible_user=ubuntu ansible_become=yes

[all:vars]
ansible_python_interpreter=/usr/bin/python3
app_name=facturation_pme
app_user=facturation_pme
app_group=facturation_pme
app_dir=/opt/facturation_pme
git_repo=https://github.com/frederickmeyapiiii/Accounting-saas.git
git_branch=main
django_port=8000
gunicorn_port=8000
nginx_port=80
